package ExceptionHandling;

public class Example1 {


	public static void ex1(){
		try {
			System.out.println("Entered Try Block");
			String[] x1 = {"a","b"};
			//	x1[0] = "abc"; // Exception occurred because Array index started from -1 where as it should be 0
			System.out.print(x1[2]);
		} catch (Exception e) {
			System.out.println("Entered Catch Block");
  			e.printStackTrace();
			throw e;
		}

	}


	public static void main(String[] args) {

		ex1();

	}

}
